[package]
name = "tach-core"
version = "0.1.0"
edition = "2021"

[dependencies]
pyo3 = { version = "0.23", features = ["auto-initialize"] }
anyhow = "1.0"
nix = { version = "0.29", features = ["process", "signal", "uio", "socket", "fs"] }

# Discovery Stack
rustpython-parser = "0.4"
rustpython-ast = "0.4"
ignore = "0.4"
